import type { MapDefinition } from "../index.js";

export const europeMap: MapDefinition = {
  id: "europe",
  name: "Europe",
  boardSize: { width: 1335, height: 872 },
  backgroundOffset: { x: 70, y: 470 },
  backgroundSvgSize: { width: 1613, height: 1417 },
  cities: [
    "London",
    "Edinburgh",
    "Amsterdam",
    "Bruxelles",
    "Paris",
    "Brest",
    "Dieppe",
    "Frankfurt",
    "Essen",
    "Berlin",
    "Danzig",
    "Copenhagen",
    "Stockholm",
    "Zurich",
    "Munich",
    "Vienna",
    "Budapest",
    "Warszawa",
    "Wilno",
    "Riga",
    "Petrograd",
    "Smolensk",
    "Moskva",
    "Kyiv",
    "Kharkov",
    "Bucharest",
    "Sofia",
    "Athina",
    "Sarajevo",
    "Zagreb",
    "Venezia",
    "Roma",
    "Brindisi",
    "Palermo",
    "Barcelona",
    "Pamplona",
    "Madrid",
    "Cadiz",
    "Lisboa",
    "Marseille",
    "Constantinople",
    "Ankara",
    "Smyrna",
    "Erzurum",
    "Sochi",
    "Sevastopol",
    "Rostov"
  ],
  cityPoints: {
    "Edinburgh": { x: 293, y: 197 },
    "London": { x: 334, y: 357 },
    "Amsterdam": { x: 435, y: 334 },
    "Bruxelles": { x: 429, y: 393 },
    "Dieppe": { x: 348, y: 414 },
    "Paris": { x: 405, y: 474 },
    "Brest": { x: 240, y: 453 },
    "Essen": { x: 510, y: 376 },
    "Frankfurt": { x: 512, y: 440 },
    "Berlin": { x: 592, y: 338 },
    "Danzig": { x: 670, y: 275 },
    "Copenhagen": { x: 583, y: 233 },
    "Stockholm": { x: 675, y: 101 },
    "Zurich": { x: 511, y: 517 },
    "Munich": { x: 585, y: 465 },
    "Vienna": { x: 669, y: 494 },
    "Budapest": { x: 745, y: 499 },
    "Warszawa": { x: 757, y: 317 },
    "Wilno": { x: 865, y: 252 },
    "Riga": { x: 800, y: 162 },
    "Petrograd": { x: 879, y: 50 },
    "Smolensk": { x: 972, y: 188 },
    "Moskva": { x: 1032, y: 116 },
    "Kyiv": { x: 968, y: 350 },
    "Kharkov": { x: 1088, y: 336 },
    "Bucharest": { x: 927, y: 560 },
    "Sofia": { x: 862, y: 633 },
    "Athina": { x: 859, y: 769 },
    "Sarajevo": { x: 745, y: 613 },
    "Zagreb": { x: 658, y: 577 },
    "Venezia": { x: 587, y: 565 },
    "Roma": { x: 593, y: 686 },
    "Brindisi": { x: 728, y: 722 },
    "Palermo": { x: 635, y: 821 },
    "Barcelona": { x: 309, y: 699 },
    "Pamplona": { x: 248, y: 630 },
    "Madrid": { x: 187, y: 713 },
    "Cadiz": { x: 121, y: 822 },
    "Lisboa": { x: 50, y: 709 },
    "Marseille": { x: 422, y: 630 },
    "Constantinople": { x: 1007, y: 653 },
    "Ankara": { x: 1139, y: 658 },
    "Smyrna": { x: 966, y: 757 },
    "Erzurum": { x: 1285, y: 604 },
    "Sochi": { x: 1195, y: 485 },
    "Sevastopol": { x: 1083, y: 515 },
    "Rostov": { x: 1176, y: 397 }
  },
  routes: [
    { id: "e1", from: "Amsterdam", to: "Bruxelles", length: 1, color: "black", routeType: "normal" },
    { id: "e2", from: "Amsterdam", to: "Essen", length: 3, color: "yellow", routeType: "normal" },
    { id: "e3", from: "Amsterdam", to: "Frankfurt", length: 2, color: "white", routeType: "normal" },
    { id: "e4", from: "Athina", to: "Brindisi", length: 4, color: "gray", routeType: "ferry", ferryLocomotives: 1 },
    { id: "e5", from: "Athina", to: "Sarajevo", length: 4, color: "green", routeType: "normal" },
    { id: "e6", from: "Athina", to: "Smyrna", length: 2, color: "gray", routeType: "ferry", ferryLocomotives: 1 },
    { id: "e7", from: "Barcelona", to: "Marseille", length: 4, color: "gray", routeType: "normal" },
    { id: "e8", from: "Barcelona", to: "Madrid", length: 2, color: "yellow", routeType: "normal" },
    { id: "e9", from: "Barcelona", to: "Pamplona", length: 2, color: "gray", routeType: "tunnel" },
    { id: "e10", from: "Berlin", to: "Danzig", length: 4, color: "gray", routeType: "normal" },
    { id: "e11", from: "Berlin", to: "Essen", length: 2, color: "blue", routeType: "normal" },
    { id: "e12", from: "Berlin", to: "Frankfurt", length: 3, color: "red", routeType: "normal" },
    { id: "e13", from: "Berlin", to: "Vienna", length: 3, color: "green", routeType: "normal" },
    { id: "e14", from: "Berlin", to: "Warszawa", length: 4, color: "pink", routeType: "double" },
    { id: "e15", from: "Brest", to: "Dieppe", length: 2, color: "orange", routeType: "normal" },
    { id: "e16", from: "Brest", to: "Paris", length: 3, color: "black", routeType: "normal" },
    { id: "e17", from: "Brest", to: "Pamplona", length: 4, color: "pink", routeType: "normal" },
    { id: "e18", from: "Brindisi", to: "Palermo", length: 3, color: "white", routeType: "ferry", ferryLocomotives: 1 },
    { id: "e19", from: "Brindisi", to: "Roma", length: 2, color: "blue", routeType: "normal" },
    { id: "e20", from: "Bruxelles", to: "Dieppe", length: 2, color: "green", routeType: "normal" },
    { id: "e21", from: "Bruxelles", to: "Paris", length: 2, color: "yellow", routeType: "normal" },
    { id: "e22", from: "Budapest", to: "Bucharest", length: 4, color: "gray", routeType: "normal" },
    { id: "e23", from: "Budapest", to: "Kyiv", length: 6, color: "gray", routeType: "normal" },
    { id: "e24", from: "Budapest", to: "Sarajevo", length: 3, color: "pink", routeType: "normal" },
    { id: "e25", from: "Budapest", to: "Vienna", length: 1, color: "red", routeType: "normal" },
    { id: "e26", from: "Bucharest", to: "Constantinople", length: 3, color: "yellow", routeType: "normal" },
    { id: "e27", from: "Bucharest", to: "Kyiv", length: 4, color: "orange", routeType: "normal" },
    { id: "e28", from: "Bucharest", to: "Sevastopol", length: 4, color: "gray", routeType: "normal" },
    { id: "e29", from: "Cadiz", to: "Lisboa", length: 2, color: "blue", routeType: "normal" },
    { id: "e30", from: "Cadiz", to: "Madrid", length: 3, color: "orange", routeType: "normal" },
    { id: "e31", from: "Constantinople", to: "Ankara", length: 2, color: "gray", routeType: "tunnel" },
    { id: "e32", from: "Constantinople", to: "Smyrna", length: 2, color: "gray", routeType: "ferry", ferryLocomotives: 1 },
    { id: "e33", from: "Constantinople", to: "Sofia", length: 3, color: "blue", routeType: "normal" },
    { id: "e34", from: "Danzig", to: "Riga", length: 3, color: "black", routeType: "normal" },
    { id: "e35", from: "Dieppe", to: "London", length: 2, color: "gray", routeType: "ferry", ferryLocomotives: 1 },
    { id: "e36", from: "Dieppe", to: "Paris", length: 1, color: "pink", routeType: "normal" },
    { id: "e37", from: "Edinburgh", to: "London", length: 4, color: "black", routeType: "double" },
    { id: "e38", from: "Essen", to: "Frankfurt", length: 2, color: "green", routeType: "normal" },
    { id: "e39", from: "Essen", to: "Copenhagen", length: 3, color: "gray", routeType: "ferry", ferryLocomotives: 1 },
    { id: "e40", from: "Frankfurt", to: "Munich", length: 2, color: "pink", routeType: "normal" },
    { id: "e41", from: "Frankfurt", to: "Paris", length: 3, color: "white", routeType: "normal" },
    { id: "e42", from: "Kyiv", to: "Moskva", length: 4, color: "white", routeType: "normal" },
    { id: "e43", from: "Kyiv", to: "Petrograd", length: 4, color: "gray", routeType: "normal" },
    { id: "e44", from: "Kyiv", to: "Sevastopol", length: 4, color: "gray", routeType: "normal" },
    { id: "e45", from: "Copenhagen", to: "Stockholm", length: 3, color: "white", routeType: "double" },
    { id: "e46", from: "Lisboa", to: "Madrid", length: 3, color: "pink", routeType: "normal" },
    { id: "e47", from: "London", to: "Edinburgh", length: 4, color: "orange", routeType: "double" },
    { id: "e48", from: "London", to: "Paris", length: 2, color: "gray", routeType: "ferry", ferryLocomotives: 1 },
    { id: "e49", from: "Madrid", to: "Pamplona", length: 3, color: "black", routeType: "tunnel" },
    { id: "e50", from: "Marseille", to: "Paris", length: 4, color: "gray", routeType: "normal" },
    { id: "e51", from: "Marseille", to: "Roma", length: 4, color: "gray", routeType: "tunnel" },
    { id: "e52", from: "Marseille", to: "Zurich", length: 2, color: "pink", routeType: "tunnel" },
    { id: "e53", from: "Moskva", to: "Petrograd", length: 4, color: "white", routeType: "normal" },
    { id: "e54", from: "Moskva", to: "Sevastopol", length: 4, color: "gray", routeType: "normal" },
    { id: "e55", from: "Moskva", to: "Smolensk", length: 2, color: "orange", routeType: "normal" },
    { id: "e56", from: "Munich", to: "Venezia", length: 2, color: "blue", routeType: "tunnel" },
    { id: "e57", from: "Munich", to: "Vienna", length: 3, color: "orange", routeType: "normal" },
    { id: "e58", from: "Munich", to: "Zurich", length: 2, color: "yellow", routeType: "tunnel" },
    { id: "e59", from: "Palermo", to: "Smyrna", length: 6, color: "orange", routeType: "ferry", ferryLocomotives: 2 },
    { id: "e60", from: "Pamplona", to: "Paris", length: 4, color: "gray", routeType: "tunnel" },
    { id: "e61", from: "Paris", to: "Zurich", length: 3, color: "gray", routeType: "tunnel" },
    { id: "e62", from: "Petrograd", to: "Riga", length: 4, color: "gray", routeType: "normal" },
    { id: "e63", from: "Petrograd", to: "Stockholm", length: 8, color: "gray", routeType: "ferry", ferryLocomotives: 2 },
    { id: "e64", from: "Roma", to: "Venezia", length: 2, color: "black", routeType: "normal" },
    { id: "e65", from: "Sarajevo", to: "Sofia", length: 2, color: "gray", routeType: "normal" },
    { id: "e66", from: "Sarajevo", to: "Zagreb", length: 3, color: "gray", routeType: "normal" },
    { id: "e67", from: "Sevastopol", to: "Sochi", length: 2, color: "gray", routeType: "normal" },
    { id: "e79", from: "Kharkov", to: "Kyiv", length: 4, color: "orange", routeType: "normal" },
    { id: "e80", from: "Kharkov", to: "Rostov", length: 2, color: "red", routeType: "normal" },
    { id: "e81", from: "Kharkov", to: "Sevastopol", length: 3, color: "black", routeType: "normal" },
    { id: "e82", from: "Rostov", to: "Kyiv", length: 2, color: "white", routeType: "normal" },
    { id: "e83", from: "Rostov", to: "Sochi", length: 3, color: "gray", routeType: "normal" },
    { id: "e84", from: "Erzurum", to: "Ankara", length: 2, color: "yellow", routeType: "normal" },
    { id: "e85", from: "Erzurum", to: "Smyrna", length: 4, color: "pink", routeType: "normal" },
    { id: "e86", from: "Erzurum", to: "Sochi", length: 4, color: "black", routeType: "normal" },
    { id: "e68", from: "Smyrna", to: "Ankara", length: 3, color: "black", routeType: "normal" },
    { id: "e69", from: "Sofia", to: "Constantinople", length: 3, color: "gray", routeType: "normal" },
    { id: "e70", from: "Stockholm", to: "Copenhagen", length: 3, color: "yellow", routeType: "double" },
    { id: "e71", from: "Venezia", to: "Zagreb", length: 2, color: "gray", routeType: "normal" },
    { id: "e72", from: "Warszawa", to: "Smolensk", length: 3, color: "yellow", routeType: "normal" },
    { id: "e76", from: "Warszawa", to: "Wilno", length: 2, color: "red", routeType: "normal" },
    { id: "e77", from: "Wilno", to: "Riga", length: 2, color: "green", routeType: "normal" },
    { id: "e78", from: "Wilno", to: "Smolensk", length: 3, color: "blue", routeType: "normal" },
    { id: "e73", from: "Warszawa", to: "Berlin", length: 4, color: "pink", routeType: "double" },
    { id: "e74", from: "Vienna", to: "Zagreb", length: 2, color: "gray", routeType: "normal" },
    { id: "e75", from: "Zurich", to: "Venezia", length: 2, color: "green", routeType: "tunnel" }
  ],
  destinationDeck: [
    { id: "ed1", from: "London", to: "Berlin", points: 7 },
    { id: "ed2", from: "Edinburgh", to: "Paris", points: 7 },
    { id: "ed3", from: "Amsterdam", to: "Roma", points: 8 },
    { id: "ed4", from: "Paris", to: "Moskva", points: 12 },
    { id: "ed5", from: "Brest", to: "Venezia", points: 8 },
    { id: "ed6", from: "Dieppe", to: "Madrid", points: 8 },
    { id: "ed7", from: "Frankfurt", to: "Sofia", points: 8 },
    { id: "ed8", from: "Essen", to: "Kyiv", points: 10 },
    { id: "ed9", from: "Berlin", to: "Bucharest", points: 8 },
    { id: "ed10", from: "Copenhagen", to: "Athina", points: 11 },
    { id: "ed11", from: "Stockholm", to: "Roma", points: 10 },
    { id: "ed12", from: "Zurich", to: "Brindisi", points: 6 },
    { id: "ed13", from: "Munich", to: "Smolensk", points: 8 },
    { id: "ed14", from: "Vienna", to: "Constantinople", points: 8 },
    { id: "ed15", from: "Budapest", to: "Madrid", points: 10 },
    { id: "ed16", from: "Warszawa", to: "Smyrna", points: 8 },
    { id: "ed17", from: "Riga", to: "Bucharest", points: 7 },
    { id: "ed18", from: "Petrograd", to: "Ankara", points: 8 },
    { id: "ed19", from: "Smolensk", to: "Barcelona", points: 12 },
    { id: "ed20", from: "Moskva", to: "Cadiz", points: 16 },
    { id: "ed21", from: "Kyiv", to: "Lisboa", points: 13 },
    { id: "ed22", from: "Kharkov", to: "Palermo", points: 14 },
    { id: "ed23", from: "Bucharest", to: "Erzurum", points: 6 },
    { id: "ed24", from: "Sofia", to: "Stockholm", points: 11 },
    { id: "ed25", from: "Athina", to: "London", points: 10 },
    { id: "ed26", from: "Sarajevo", to: "Berlin", points: 7 },
    { id: "ed27", from: "Zagreb", to: "Bruxelles", points: 8 },
    { id: "ed28", from: "Roma", to: "Constantinople", points: 10 },
    { id: "ed29", from: "Barcelona", to: "Brest", points: 6 },
    { id: "ed30", from: "Lisboa", to: "Petrograd", points: 20 },
    { id: "ed31", from: "Marseille", to: "Essen", points: 8 },
    { id: "ed32", from: "Constantinople", to: "Madrid", points: 13 },
    { id: "ed33", from: "Ankara", to: "London", points: 13 },
    { id: "ed34", from: "Smyrna", to: "Palermo", points: 8 },
    { id: "ed35", from: "Erzurum", to: "Amsterdam", points: 14 },
    { id: "ed36", from: "Sochi", to: "Paris", points: 12 },
    { id: "ed37", from: "Sevastopol", to: "Madrid", points: 14 },
    { id: "ed38", from: "Rostov", to: "Berlin", points: 10 }
  ]
};

