import type { MapDefinition } from "../index.js";

export const usaMap: MapDefinition = {
  id: "usa",
  name: "USA",
  cities: [
    "Seattle",
    "Portland",
    "San Francisco",
    "Los Angeles",
    "Las Vegas",
    "Salt Lake City",
    "Phoenix",
    "Santa Fe",
    "El Paso",
    "Denver",
    "Helena",
    "Calgary",
    "Winnipeg",
    "Sault St. Marie",
    "Duluth",
    "Omaha",
    "Kansas City",
    "Oklahoma City",
    "Dallas",
    "Houston",
    "New Orleans",
    "Little Rock",
    "Saint Louis",
    "Chicago",
    "Pittsburgh",
    "Toronto",
    "Montreal",
    "Boston",
    "New York",
    "Washington",
    "Raleigh",
    "Charleston",
    "Nashville",
    "Atlanta",
    "Miami"
  ],
  routes: [
    { id: "r1", from: "Seattle", to: "Portland", length: 1, color: "gray" },
    { id: "r2", from: "Portland", to: "San Francisco", length: 5, color: "green" },
    { id: "r3", from: "San Francisco", to: "Los Angeles", length: 3, color: "pink" },
    { id: "r4", from: "Los Angeles", to: "Las Vegas", length: 2, color: "gray" },
    { id: "r5", from: "Las Vegas", to: "Salt Lake City", length: 3, color: "orange" },
    { id: "r6", from: "Seattle", to: "Helena", length: 6, color: "yellow" },
    { id: "r7", from: "Seattle", to: "Calgary", length: 4, color: "gray" },
    { id: "r8", from: "Portland", to: "Salt Lake City", length: 6, color: "blue" },
    { id: "r9", from: "San Francisco", to: "Salt Lake City", length: 5, color: "orange" },
    { id: "r10", from: "Los Angeles", to: "Phoenix", length: 3, color: "gray" },
    { id: "r11", from: "Los Angeles", to: "El Paso", length: 6, color: "black" },
    { id: "r12", from: "Phoenix", to: "El Paso", length: 3, color: "gray" },
    { id: "r13", from: "Phoenix", to: "Santa Fe", length: 3, color: "gray" },
    { id: "r14", from: "Las Vegas", to: "Denver", length: 5, color: "gray" },
    { id: "r15", from: "Salt Lake City", to: "Denver", length: 3, color: "red" },
    { id: "r16", from: "Salt Lake City", to: "Helena", length: 3, color: "pink" },
    { id: "r17", from: "Calgary", to: "Winnipeg", length: 6, color: "white" },
    { id: "r18", from: "Calgary", to: "Helena", length: 4, color: "gray" },
    { id: "r19", from: "Helena", to: "Winnipeg", length: 4, color: "blue" },
    { id: "r20", from: "Helena", to: "Duluth", length: 6, color: "orange" },
    { id: "r21", from: "Helena", to: "Denver", length: 4, color: "green" },
    { id: "r22", from: "Helena", to: "Omaha", length: 5, color: "red" },
    { id: "r23", from: "Denver", to: "Santa Fe", length: 2, color: "gray" },
    { id: "r24", from: "Denver", to: "Kansas City", length: 4, color: "black" },
    { id: "r25", from: "Denver", to: "Oklahoma City", length: 4, color: "red" },
    { id: "r26", from: "Denver", to: "Omaha", length: 4, color: "pink" },
    { id: "r27", from: "Santa Fe", to: "El Paso", length: 2, color: "gray" },
    { id: "r28", from: "Santa Fe", to: "Oklahoma City", length: 3, color: "blue" },
    { id: "r29", from: "El Paso", to: "Dallas", length: 4, color: "red" },
    { id: "r30", from: "El Paso", to: "Houston", length: 6, color: "green" },
    { id: "r31", from: "El Paso", to: "Oklahoma City", length: 5, color: "yellow" },
    { id: "r32", from: "Winnipeg", to: "Sault St. Marie", length: 6, color: "gray" },
    { id: "r33", from: "Winnipeg", to: "Duluth", length: 4, color: "black" },
    { id: "r34", from: "Duluth", to: "Sault St. Marie", length: 3, color: "gray" },
    { id: "r35", from: "Duluth", to: "Toronto", length: 6, color: "pink" },
    { id: "r36", from: "Duluth", to: "Chicago", length: 3, color: "red" },
    { id: "r37", from: "Duluth", to: "Omaha", length: 2, color: "gray" },
    { id: "r38", from: "Omaha", to: "Kansas City", length: 1, color: "gray" },
    { id: "r39", from: "Kansas City", to: "Saint Louis", length: 2, color: "blue" },
    { id: "r40", from: "Kansas City", to: "Oklahoma City", length: 2, color: "gray" },
    { id: "r41", from: "Kansas City", to: "Little Rock", length: 2, color: "gray" },
    { id: "r42", from: "Oklahoma City", to: "Dallas", length: 2, color: "gray" },
    { id: "r43", from: "Dallas", to: "Houston", length: 1, color: "gray" },
    { id: "r44", from: "Dallas", to: "Little Rock", length: 2, color: "gray" },
    { id: "r45", from: "Houston", to: "New Orleans", length: 2, color: "gray" },
    { id: "r46", from: "New Orleans", to: "Atlanta", length: 4, color: "yellow" },
    { id: "r47", from: "New Orleans", to: "Miami", length: 6, color: "red" },
    { id: "r48", from: "New Orleans", to: "Little Rock", length: 3, color: "green" },
    { id: "r49", from: "Little Rock", to: "Saint Louis", length: 2, color: "gray" },
    { id: "r50", from: "Little Rock", to: "Nashville", length: 3, color: "white" },
    { id: "r51", from: "Saint Louis", to: "Chicago", length: 2, color: "green" },
    { id: "r52", from: "Saint Louis", to: "Nashville", length: 2, color: "gray" },
    { id: "r53", from: "Chicago", to: "Pittsburgh", length: 3, color: "black" },
    { id: "r54", from: "Chicago", to: "Toronto", length: 4, color: "white" },
    { id: "r55", from: "Sault St. Marie", to: "Montreal", length: 5, color: "black" },
    { id: "r56", from: "Sault St. Marie", to: "Toronto", length: 2, color: "gray" },
    { id: "r57", from: "Toronto", to: "Pittsburgh", length: 2, color: "gray" },
    { id: "r58", from: "Toronto", to: "Montreal", length: 3, color: "gray" },
    { id: "r59", from: "Montreal", to: "Boston", length: 2, color: "gray" },
    { id: "r60", from: "Montreal", to: "New York", length: 3, color: "blue" },
    { id: "r61", from: "Boston", to: "New York", length: 2, color: "yellow" },
    { id: "r62", from: "New York", to: "Washington", length: 2, color: "black" },
    { id: "r63", from: "Washington", to: "Raleigh", length: 2, color: "gray" },
    { id: "r64", from: "Pittsburgh", to: "New York", length: 2, color: "green" },
    { id: "r65", from: "Pittsburgh", to: "Washington", length: 2, color: "gray" },
    { id: "r66", from: "Pittsburgh", to: "Raleigh", length: 2, color: "gray" },
    { id: "r67", from: "Pittsburgh", to: "Nashville", length: 4, color: "yellow" },
    { id: "r68", from: "Nashville", to: "Raleigh", length: 3, color: "black" },
    { id: "r69", from: "Nashville", to: "Atlanta", length: 1, color: "gray" },
    { id: "r70", from: "Raleigh", to: "Charleston", length: 2, color: "gray" },
    { id: "r71", from: "Raleigh", to: "Atlanta", length: 2, color: "gray" },
    { id: "r72", from: "Charleston", to: "Atlanta", length: 2, color: "gray" },
    { id: "r73", from: "Charleston", to: "Miami", length: 4, color: "pink" },
    { id: "r74", from: "Atlanta", to: "Miami", length: 5, color: "blue" },
    { id: "r75", from: "Omaha", to: "Chicago", length: 4, color: "blue" },
    { id: "r76", from: "Kansas City", to: "Chicago", length: 4, color: "orange" },
    { id: "r77", from: "Oklahoma City", to: "Little Rock", length: 2, color: "gray" },
    { id: "r78", from: "Santa Fe", to: "Denver", length: 2, color: "gray" }
  ],
  destinationDeck: [
    { id: "d1", from: "Seattle", to: "Los Angeles", points: 9 },
    { id: "d2", from: "Seattle", to: "New York", points: 22 },
    { id: "d3", from: "Seattle", to: "Miami", points: 20 },
    { id: "d4", from: "Portland", to: "Nashville", points: 17 },
    { id: "d5", from: "San Francisco", to: "Atlanta", points: 17 },
    { id: "d6", from: "Los Angeles", to: "New York", points: 21 },
    { id: "d7", from: "Los Angeles", to: "Miami", points: 20 },
    { id: "d8", from: "Calgary", to: "Salt Lake City", points: 7 },
    { id: "d9", from: "Calgary", to: "Phoenix", points: 13 },
    { id: "d10", from: "Calgary", to: "Houston", points: 13 },
    { id: "d11", from: "Helena", to: "Los Angeles", points: 8 },
    { id: "d12", from: "Winnipeg", to: "Little Rock", points: 11 },
    { id: "d13", from: "Winnipeg", to: "Houston", points: 12 },
    { id: "d14", from: "Duluth", to: "El Paso", points: 10 },
    { id: "d15", from: "Duluth", to: "Houston", points: 8 },
    { id: "d16", from: "Sault St. Marie", to: "Oklahoma City", points: 9 },
    { id: "d17", from: "Montreal", to: "Atlanta", points: 9 },
    { id: "d18", from: "Montreal", to: "New Orleans", points: 13 },
    { id: "d19", from: "Boston", to: "Miami", points: 12 },
    { id: "d20", from: "Toronto", to: "Miami", points: 10 },
    { id: "d21", from: "Chicago", to: "Santa Fe", points: 9 },
    { id: "d22", from: "Chicago", to: "New Orleans", points: 7 },
    { id: "d23", from: "Denver", to: "Pittsburgh", points: 11 },
    { id: "d24", from: "Denver", to: "El Paso", points: 4 },
    { id: "d25", from: "Kansas City", to: "Houston", points: 5 },
    { id: "d26", from: "Omaha", to: "Dallas", points: 6 },
    { id: "d27", from: "Saint Louis", to: "Miami", points: 12 },
    { id: "d28", from: "New York", to: "Atlanta", points: 6 },
    { id: "d29", from: "New York", to: "New Orleans", points: 8 },
    { id: "d30", from: "Washington", to: "Miami", points: 8 }
  ]
};

