import type { LabelOffset, Point } from "../mapLayoutTypes";

const EUROPE_BOARD = { width: 1335, height: 872 };

type EuropeCityLayout = Point & { label: LabelOffset };

// const europeCities: Record<string, EuropeCityLayout> = {
//   Edinburgh: { x: 268, y: 232, label: { dx: 10, dy: -18 } },
//   London: { x: 309, y: 392, label: { dx: -90, dy: -10 } },
//   Amsterdam: { x: 410, y: 369, label: { dx: 12, dy: -16 } },
//   Bruxelles: { x: 404, y: 428, label: { dx: 12, dy: 10 } },
//   Dieppe: { x: 323, y: 449, label: { dx: 0, dy: -30 } },
//   Paris: { x: 380, y: 509, label: { dx: -80, dy: 10 } },
//   Brest: { x: 215, y: 488, label: { dx: -70, dy: -10 } },
//   Essen: { x: 485, y: 411, label: { dx: 8, dy: 12 } },
//   Frankfurt: { x: 487, y: 475, label: { dx: -60, dy: 20 } },
//   Berlin: { x: 567, y: 373, label: { dx: -10, dy: -30 } },
//   Danzig: { x: 645, y: 310, label: { dx: 10, dy: -18 } },
//   Copenhagen: { x: 558, y: 268, label: { dx: 8, dy: -2 } },
//   Stockholm: { x: 650, y: 136, label: { dx: -120, dy: -20 } },
//   Zurich: { x: 486, y: 552, label: { dx: -55, dy: 10 } },
//   Munich: { x: 560, y: 500, label: { dx: 5, dy: -25 } },
//   Vienna: { x: 644, y: 529, label: { dx: -25, dy: 15 } },
//   Budapest: { x: 720, y: 534, label: { dx: 5, dy: -30 } },
//   Warszawa: { x: 732, y: 352, label: { dx: 10, dy: 10 } },
//   Wilno: { x: 840, y: 287, label: { dx: 10, dy: -20 } },
//   Riga: { x: 775, y: 197, label: { dx: 10, dy: 0 } },
//   Petrograd: { x: 854, y: 85, label: { dx: 10, dy: -20 } },
//   Smolensk: { x: 947, y: 223, label: { dx: 10, dy: 0 } },
//   Moskva: { x: 1007, y: 151, label: { dx: 10, dy: -10 } },
//   Kyiv: { x: 943, y: 385, label: { dx: 10, dy: 15 } },
//   Kharkov: { x: 1063, y: 371, label: { dx: 15, dy: -20 } },
//   Bucharest: { x: 902, y: 595, label: { dx: 10, dy: 12 } },
//   Sofia: { x: 837, y: 668, label: { dx: 10, dy: 15 } },
//   Athina: { x: 834, y: 804, label: { dx: -35, dy: 10 } },
//   Sarajevo: { x: 720, y: 648, label: { dx: -40, dy: 12 } },
//   Zagreb: { x: 633, y: 612, label: { dx: 5, dy: -30 } },
//   Venezia: { x: 562, y: 600, label: { dx: -100, dy: 5 } },
//   Roma: { x: 568, y: 721, label: { dx: -50, dy: 10 } },
//   Brindisi: { x: 703, y: 757, label: { dx: -60, dy: 10 } },
//   Palermo: { x: 610, y: 856, label: { dx: -30, dy: 15 } },
//   Barcelona: { x: 284, y: 734, label: { dx: 8, dy: 14 } },
//   Pamplona: { x: 223, y: 665, label: { dx: 8, dy: -18 } },
//   Madrid: { x: 162, y: 748, label: { dx: -35, dy: -35 } },
//   Cadiz: { x: 96, y: 857, label: { dx: 8, dy: 0 } },
//   Lisboa: { x: 25, y: 744, label: { dx: -20, dy: 20 } },
//   Marseille: { x: 397, y: 665, label: { dx: -100, dy: -20 } },
//   Constantinople: { x: 982, y: 688, label: { dx: 0, dy: -30 } },
//   Ankara: { x: 1114, y: 693, label: { dx: 10, dy: 12 } },
//   Smyrna: { x: 971, y: 812, label: { dx: 20, dy: 10 } },
//   Erzurum: { x: 1260, y: 639, label: { dx: -30, dy: 20 } },
//   Sochi: { x: 1170, y: 520, label: { dx: 10, dy: 8 } },
//   Sevastopol: { x: 1058, y: 550, label: { dx: 10, dy: -10 } },
//   Rostov: { x: 1151, y: 432, label: { dx: 20, dy: -10 } },
// };

// Generated by calibrator on 2026-04-09T17:49:25.529Z
const europeCities: Record<string, { x: number; y: number; label: { dx: number; dy: number } }> = {
  Edinburgh: { x: 268, y: 232, label: { dx: 10, dy: -18 } },
  London: { x: 309, y: 392, label: { dx: -90, dy: -10 } },
  Amsterdam: { x: 410, y: 369, label: { dx: -56, dy: -35 } },
  Bruxelles: { x: 404, y: 428, label: { dx: 10, dy: 2 } },
  Dieppe: { x: 323, y: 449, label: { dx: -69, dy: -15 } },
  Paris: { x: 380, y: 509, label: { dx: -94, dy: 1 } },
  Brest: { x: 215, y: 488, label: { dx: -70, dy: -10 } },
  Essen: { x: 485, y: 411, label: { dx: -17, dy: -25 } },
  Frankfurt: { x: 487, y: 475, label: { dx: -39, dy: 20 } },
  Berlin: { x: 567, y: 373, label: { dx: -35, dy: -34 } },
  Danzig: { x: 645, y: 310, label: { dx: -46, dy: -33 } },
  Copenhagen: { x: 546, y: 254, label: { dx: -109, dy: -24 } },
  Stockholm: { x: 641, y: 132, label: { dx: -46, dy: -35 } },
  Zurich: { x: 486, y: 552, label: { dx: -55, dy: 10 } },
  Munich: { x: 560, y: 500, label: { dx: 10, dy: -28 } },
  Vienna: { x: 644, y: 529, label: { dx: -56, dy: 6 } },
  Budapest: { x: 720, y: 534, label: { dx: 32, dy: -15 } },
  Warszawa: { x: 732, y: 352, label: { dx: 7, dy: 16 } },
  Wilno: { x: 806, y: 272, label: { dx: 24, dy: -4 } },
  Riga: { x: 775, y: 197, label: { dx: -50, dy: -12 } },
  Petrograd: { x: 854, y: 85, label: { dx: 10, dy: -20 } },
  Smolensk: { x: 947, y: 223, label: { dx: 10, dy: 0 } },
  Moskva: { x: 1007, y: 151, label: { dx: 18, dy: -12 } },
  Kyiv: { x: 966, y: 385, label: { dx: 6, dy: 10 } },
  Kharkov: { x: 1081, y: 370, label: { dx: 15, dy: -20 } },
  Bucharest: { x: 868, y: 590, label: { dx: 51, dy: 13 } },
  Sofia: { x: 837, y: 668, label: { dx: 10, dy: 15 } },
  Athina: { x: 834, y: 804, label: { dx: 20, dy: -23 } },
  Sarajevo: { x: 720, y: 648, label: { dx: -61, dy: 20 } },
  Zagreb: { x: 633, y: 612, label: { dx: 21, dy: -18 } },
  Venezia: { x: 562, y: 600, label: { dx: -90, dy: 3 } },
  Roma: { x: 568, y: 721, label: { dx: -34, dy: 20 } },
  Brindisi: { x: 703, y: 757, label: { dx: -8, dy: 24 } },
  Palermo: { x: 610, y: 856, label: { dx: -15, dy: 23 } },
  Barcelona: { x: 284, y: 734, label: { dx: 21, dy: 16 } },
  Pamplona: { x: 223, y: 665, label: { dx: -106, dy: -22 } },
  Madrid: { x: 161, y: 748, label: { dx: -86, dy: -33 } },
  Cadiz: { x: 79, y: 857, label: { dx: 15, dy: 13 } },
  Lisboa: { x: 14, y: 766, label: { dx: -24, dy: -32 } },
  Marseille: { x: 397, y: 665, label: { dx: -5, dy: 25 } },
  Constantinople: { x: 982, y: 688, label: { dx: 0, dy: -30 } },
  Ankara: { x: 1114, y: 693, label: { dx: 10, dy: 12 } },
  Smyrna: { x: 971, y: 812, label: { dx: 8, dy: 14 } },
  Erzurum: { x: 1260, y: 639, label: { dx: -30, dy: 20 } },
  Sochi: { x: 1177, y: 503, label: { dx: 15, dy: 11 } },
  Sevastopol: { x: 1058, y: 550, label: { dx: -30, dy: 22 } },
  Rostov: { x: 1161, y: 425, label: { dx: 20, dy: -10 } },
};

// board: { width: 1335, height: 872 }
// backgroundOffset: { x: 70, y: 470 }
// backgroundSvgSize: { width: 1613, height: 1417 }
// board: { width: 1335, height: 872 }
// backgroundOffset: { x: 70, y: 470 }
// backgroundSvgSize: { width: 1613, height: 1417 }
// board: { width: 1335, height: 872 }
// backgroundOffset: { x: 70, y: 470 }
// backgroundSvgSize: { width: 1613, height: 1417 }

// board: { width: 1335, height: 872 }
// backgroundOffset: { x: 70, y: 470 }
// backgroundSvgSize: { width: 1613, height: 1417 }

// board: { width: 1335, height: 872 }
// backgroundOffset: { x: 70, y: 470 }
// backgroundSvgSize: { width: 1613, height: 1417 }

// board: { width: 1335, height: 872 }
// backgroundOffset: { x: 70, y: 470 }
// backgroundSvgSize: { width: 1613, height: 1417 }

const europeCityPoints: Record<string, Point> = Object.fromEntries(
  Object.entries(europeCities).map(([name, city]) => [name, { x: city.x, y: city.y }]),
) as Record<string, Point>;

const europeCityLabelOffsets: Record<string, LabelOffset> = Object.fromEntries(
  Object.entries(europeCities).map(([name, city]) => [name, city.label]),
) as Record<string, LabelOffset>;

export const EUROPE_LAYOUT = {
  board: EUROPE_BOARD,
  cityPoints: europeCityPoints,
  cityLabelOffsets: europeCityLabelOffsets,
  backgroundSvg: "/assets/maps/europe.svg",
  backgroundSvgSize: { width: 1613, height: 1417 },
  backgroundOffset: { x: 70, y: 470 },
};

